// Copyright (c) Rivoli AI 2026. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using Andy.Policies.Shared.Auditing;
using FluentAssertions;
using Xunit;

namespace Andy.Policies.Tests.Unit.Audit;

/// <summary>
/// P6.8 (#50) — golden-vector tests for
/// <see cref="AuditEnvelopeHasher.ComputeHash"/>. Pin five
/// fixed (prevHash, payload) inputs to hard-coded SHA-256 hex
/// outputs so any change to the canonical-JSON envelope shape
/// (key set, key names, ordering, timestamp format, etc.)
/// becomes a noisy test failure rather than a silent re-hashing
/// of every audit row in production.
/// </summary>
/// <remarks>
/// <para>
/// Golden hex values were generated by running the production
/// hasher on the same inputs once and pasting the result.
/// The test thus pins "the algorithm at this revision produces
/// these bytes for these inputs"; flipping any of those
/// behaviours (swapping key order, adding/removing a field,
/// changing the timestamp format, switching from raw UTF-8 to
/// \\uXXXX escapes) will surface here.
/// </para>
/// <para>
/// ADR 0006 (P6.9) will pin the algorithm authoritatively;
/// these vectors are the runtime guard.
/// </para>
/// </remarks>
public class HashChainGoldenVectorsTests
{
    private static byte[] Genesis32 => new byte[32];

    private static byte[] FilledHash(byte fill)
    {
        var b = new byte[32];
        Array.Fill(b, fill);
        return b;
    }

    [Fact]
    public void GoldenVector_GenesisEvent()
    {
        var hash = AuditEnvelopeHasher.ComputeHash(
            Genesis32,
            id: Guid.Parse("11111111-1111-1111-1111-111111111111"),
            timestamp: new DateTimeOffset(2026, 5, 1, 12, 0, 0, TimeSpan.Zero),
            actorSubjectId: "user:test",
            actorRoles: new[] { "admin" },
            action: "policy.create",
            entityType: "Policy",
            entityId: "00000000-0000-0000-0000-000000000001",
            fieldDiffJson: "[]",
            rationale: "first event");

        Convert.ToHexString(hash).ToLowerInvariant()
            .Should().Be("1e9953b1a37c2ce4009212ff635da95cc5bee54737c534b20147de62348dc6b7");
    }

    [Fact]
    public void GoldenVector_NullRationale()
    {
        var hash = AuditEnvelopeHasher.ComputeHash(
            Genesis32,
            id: Guid.Parse("22222222-2222-2222-2222-222222222222"),
            timestamp: new DateTimeOffset(2026, 5, 1, 12, 0, 1, TimeSpan.Zero),
            actorSubjectId: "user:test",
            actorRoles: new[] { "admin" },
            action: "policy.update",
            entityType: "Policy",
            entityId: "00000000-0000-0000-0000-000000000002",
            fieldDiffJson: "[]",
            rationale: null);

        Convert.ToHexString(hash).ToLowerInvariant()
            .Should().Be("2f87e1cba8708e6746317737751dfefd56ccf0e3af71e1e18ac815ce166c9e07");
    }

    [Fact]
    public void GoldenVector_WithFieldDiff()
    {
        var hash = AuditEnvelopeHasher.ComputeHash(
            FilledHash(0xAB),
            id: Guid.Parse("33333333-3333-3333-3333-333333333333"),
            timestamp: new DateTimeOffset(2026, 5, 1, 12, 0, 2, TimeSpan.Zero),
            actorSubjectId: "user:alice",
            actorRoles: new[] { "approver", "author" },
            action: "policy.version.publish",
            entityType: "PolicyVersion",
            entityId: "00000000-0000-0000-0000-000000000003",
            fieldDiffJson: """[{"op":"replace","path":"/state","value":"Active"}]""",
            rationale: "promoted to Active");

        Convert.ToHexString(hash).ToLowerInvariant()
            .Should().Be("6ff4dbeded661c2f22bbbca5e24861ebef1f0b5cfa98d94cea585a49ee5b5784");
    }

    [Fact]
    public void GoldenVector_RoleOrderInvariant()
    {
        // Two callers supplying the same roles in different
        // orders must produce the same hash. The byte-exact
        // invariant proves the hasher's lex sort is in effect.
        var alpha = AuditEnvelopeHasher.ComputeHash(
            Genesis32,
            id: Guid.Parse("44444444-4444-4444-4444-444444444444"),
            timestamp: new DateTimeOffset(2026, 5, 1, 12, 0, 3, TimeSpan.Zero),
            actorSubjectId: "user:test",
            actorRoles: new[] { "admin", "author" },
            action: "policy.update",
            entityType: "Policy",
            entityId: "00000000-0000-0000-0000-000000000004",
            fieldDiffJson: "[]",
            rationale: null);
        var omega = AuditEnvelopeHasher.ComputeHash(
            Genesis32,
            id: Guid.Parse("44444444-4444-4444-4444-444444444444"),
            timestamp: new DateTimeOffset(2026, 5, 1, 12, 0, 3, TimeSpan.Zero),
            actorSubjectId: "user:test",
            actorRoles: new[] { "author", "admin" },
            action: "policy.update",
            entityType: "Policy",
            entityId: "00000000-0000-0000-0000-000000000004",
            fieldDiffJson: "[]",
            rationale: null);

        alpha.Should().Equal(omega);
        Convert.ToHexString(alpha).ToLowerInvariant()
            .Should().Be("f1d5aeb81d68fdc956c87edfe8158157230a38544b37895c7f39ec23d39f4c3a");
    }

    [Fact]
    public void GoldenVector_NonAsciiRationale()
    {
        // Catches a regression in CanonicalJson's UTF-8 output
        // path: assignable code points must travel as raw UTF-8
        // bytes (RFC 8785 §3.2.2.2), not as \\uXXXX escapes.
        var hash = AuditEnvelopeHasher.ComputeHash(
            Genesis32,
            id: Guid.Parse("55555555-5555-5555-5555-555555555555"),
            timestamp: new DateTimeOffset(2026, 5, 1, 12, 0, 4, TimeSpan.Zero),
            actorSubjectId: "user:test",
            actorRoles: Array.Empty<string>(),
            action: "policy.update",
            entityType: "Policy",
            entityId: "00000000-0000-0000-0000-000000000005",
            fieldDiffJson: "[]",
            rationale: "héllo 中文");

        Convert.ToHexString(hash).ToLowerInvariant()
            .Should().Be("9b1c4c850cbaaa591110ef629641705e21a4f00f638ea4af6710b2596d265bf8");
    }
}
